vtx_sel_CC: ( acos(cos(SDVSecVtx_L_phi-MET_phi))<1.5 )&&(SDVSecVtx_LxySig>=20.)&&(SDVSecVtx_pAngle>0.2)&&(SDVSecVtx_nGoodTrack>=2)&&( acos(cos(SDVSecVtx_L_phi-Jet_phi[0]))>1 ) && (SDVSecVtx_ndof>1)
vtx_sel_ML: ( acos(cos(SDVSecVtx_L_phi-MET_phi))<1.5 ) && (SDVSecVtx_ParTScore>0.98) && ( acos(cos(SDVSecVtx_L_phi-Jet_phi[0]))>1 )

presel: MET_pt>200&&HLT_PFMET120_PFMHT120_IDTight && Jet_pt[0]>100 && !nMuon && !nPhoton
  && !nTau && !nElectron && Flag_METFilters && Jet_chHEF[0]>0.1 && Jet_neHEF[0]<0.8
new_variables:
  #SDVTrack_isGoodTrack: ( (abs(SDVTrack_dxy)/SDVTrack_dxyError)>4 ) && (SDVTrack_normalizedChi2 < 5) && (SDVTrack_numberOfValidHits>13) && ( (SDVTrack_ptError/SDVTrack_pt)<0.015 ) 
  SDVTrack_isGoodTrack: ( (abs(SDVTrack_dxy)/SDVTrack_dxyError)>4 ) && (SDVTrack_normalizedChi2 < 5) && (abs(SDVTrack_dz)<4.) && (SDVTrack_numberOfValidHits>13) && ( (SDVTrack_ptError/SDVTrack_pt)<0.015 ) && ( acos(cos(SDVTrack_phi-Jet_phi[0]))>1 ) && ( acos(cos(SDVTrack_phi-MET_phi))<1.5 )
  SDVSecVtx_nGoodTrack: SDVSecVtx_nGoodTrack(SDVIdxLUT_SecVtxIdx,SDVIdxLUT_TrackIdx,SDVTrack_isGoodTrack,nSDVSecVtx)
  nSDVSecVtx_CCsel: ['Sum({0})', vtx_sel_CC]
  nSDVSecVtx_MLsel: ['Sum({0})', vtx_sel_ML]
  SDVSecVtx_LxySig_CCsel_max: ['Max(SDVSecVtx_LxySig[{0}])',vtx_sel_CC]
  SDVSecVtx_LxySig_MLsel_max: ['Max(SDVSecVtx_LxySig[{0}])',vtx_sel_ML]
  #SDVSecVtx_dphi_L_MET: acos(cos(SDVSecVtx_L_phi-MET_phi))
regions:
  All: 
  #CCSR: nSDVSecVtx_CCsel>0
  #MLSR: nSDVSecVtx_MLsel>0
event_variables:
- nSDVSecVtx_CCsel
- nSDVSecVtx_MLsel
- SDVSecVtx_LxySig_CCsel_max
- SDVSecVtx_LxySig_MLsel_max
- MET_pt
event_2d_plots:
- [MET_pt,SDVSecVtx_LxySig_MLsel_max]
objects:
  SDVSecVtx:
    selections:
      #genmatch: SDVSecVtx_matchedLLPnDau_bydau>1
      #genmatchtag: SDVSecVtx_matchedLLPnDau_bydau>1 && SDVSecVtx_ParTScore>0.98
      tag: SDVSecVtx_ParTScore>0.98
      untag: SDVSecVtx_ParTScore<0.98
    variables:
    - SDVSecVtx_x
    - SDVSecVtx_y
    - SDVSecVtx_nTracks
    - SDVSecVtx_pAngle
    - SDVSecVtx_nGoodTrack
    - SDVSecVtx_dlen
    - SDVSecVtx_dlenSig
    - SDVSecVtx_dlen_err
    - SDVSecVtx_Lxy
    - SDVSecVtx_LxySig
    - SDVSecVtx_Lxy_err
    - SDVSecVtx_chi2
    - SDVSecVtx_normalizedChi2
    - SDVSecVtx_ndof
    - SDVSecVtx_L_eta_abs
    - SDVSecVtx_matchedLLPIdx_bydau
    - SDVSecVtx_matchedLLPnDau_bydau
    - SDVSecVtx_TkMaxdphi
    - SDVSecVtx_TkMindphi
    - SDVSecVtx_TkMaxdeta
    - SDVSecVtx_TkMindeta
    - SDVSecVtx_TkMaxdR
    - SDVSecVtx_TkMindR
    - SDVSecVtx_dphi_L_MET
    - SDVSecVtx_dphi_L_jet0
    2d_plots:
    - [SDVSecVtx_Lxy,SDVSecVtx_pAngle]
    - [SDVSecVtx_x,SDVSecVtx_y]

plot_setting:
  LHE_HT: [LHE_HT, ';LHE HT (GeV);A.U.', 500, 0, 5000]
  MET_pt: [MET_pt, ';MET (GeV);A.U.', 100, 0, 1000]
  SDVSecVtx_x: [SDVSecVtx_x, ';vertex x (cm);A.U.',400, -20, 20]
  SDVSecVtx_y: [SDVSecVtx_y, ';vertex y (cm);A.U.',400, -20, 20]
  SDVSecVtx_L_eta_abs: [SDVSecVtx_L_eta_abs, ';vertex |#eta|;A.U.', 200, 0, 10]
  SDVSecVtx_Lxy: [SDVSecVtx_Lxy, ';vertex L_{xy} (cm);A.U.', 100, 0, 10]
  SDVSecVtx_LxySig: [SDVSecVtx_LxySig, ';vertex L_{xy}/#sigmaL_{xy};A.U.', 500, 0, 100]
  SDVSecVtx_LxySig_CCsel_max: [SDVSecVtx_LxySig_CCsel_max, ';max vertex (CC) L_{xy}/#sigma_{L_{xy}};A.U.', 100, 0, 100]
  SDVSecVtx_LxySig_MLsel_max: [SDVSecVtx_LxySig_MLsel_max, ';max vertex (ML) L_{xy}/#sigma_{L_{xy}};A.U.', 100, 0, 100]
  SDVSecVtx_Lxy_err: [SDVSecVtx_Lxy_err, ';vertex #sigmaL_{xy} (cm);A.U.', 100, 0, 0.5]
  SDVSecVtx_ParTScore: [SDVSecVtx_ParTScore, ';ParTScore;A.U.', 50, 0, 1]
  SDVSecVtx_TkMaxdR: [SDVSecVtx_TkMaxdR, ';vertex track max(dR);A.U.', 100, 0, 5]
  SDVSecVtx_TkMaxdeta: [SDVSecVtx_TkMaxdeta, ';vertex track max(d#eta);A.U.', 100, 0, 5]
  SDVSecVtx_TkMaxdphi: [SDVSecVtx_TkMaxdphi, ';vertex track max(d#phi);A.U.', 64, 0, 3.2]
  SDVSecVtx_TkMindR: [SDVSecVtx_TkMindR, ';vertex track min(dR);A.U.', 100, 0, 5]
  SDVSecVtx_TkMindeta: [SDVSecVtx_TkMindeta, ';vertex track min(d#eta);A.U.', 100, 0, 5]
  SDVSecVtx_TkMindphi: [SDVSecVtx_TkMindphi, ';vertex track min(d#phi);A.U.', 64, 0, 3.2]
  SDVSecVtx_chi2: [SDVSecVtx_chi2, ';vertex chi2;A.U.', 50, 0, 10]
  SDVSecVtx_dlen: [SDVSecVtx_dlen, ';vertex dlen (cm);A.U.', 100, 0, 10]
  SDVSecVtx_dlenSig: [SDVSecVtx_dlenSig, ';vertex dlen/#sigmadlen;A.U.', 500, 0, 100]
  SDVSecVtx_dlen_err: [SDVSecVtx_dlen_err, ';vertex #sigmadlen (cm);A.U.', 100, 0, 0.5]
  SDVSecVtx_dphi_L_MET: [SDVSecVtx_dphi_L_MET, ';#Delta#phi(Lxy,MET)', 64, 0, 3.2]
  SDVSecVtx_dphi_L_jet0: [SDVSecVtx_dphi_L_jet0, ';#Delta#phi(Lxy,jet0)', 64, 0, 3.2]
  SDVSecVtx_matchedLLPIdx_bydau: [SDVSecVtx_matchedLLPIdx_bydau, ';vertex matched LLP idx;A.U.', 5, -1, 4]
  SDVSecVtx_matchedLLPnDau_bydau: [SDVSecVtx_matchedLLPnDau_bydau, ';vertex number of tracks matched with LLP;A.U.', 10, 0, 10]
  SDVSecVtx_nGoodTrack: [SDVSecVtx_nGoodTrack, ';vertex ngoodTrack;A.U.', 20, 0, 20]
  SDVSecVtx_nTracks: [SDVSecVtx_nTracks, ';vertex nTracks;A.U.', 20, 0, 20]
  SDVSecVtx_ndof: [SDVSecVtx_ndof, ';vertex ndof;A.U.', 20, 0, 20]
  SDVSecVtx_normalizedChi2: [SDVSecVtx_normalizedChi2, ';vertex norm chi2;A.U.', 50, 0, 10]
  SDVSecVtx_pAngle: [SDVSecVtx_pAngle, ';vertex pAngle;A.U.', 64, 0, 3.2]
  nSDVSecVtx_CCsel: [nSDVSecVtx_CCsel, ';Number of vertices (CC);A.U.', 20, 0, 20]
  nSDVSecVtx_MLsel: [nSDVSecVtx_MLsel, ';Number of vertices (ML);A.U.', 20, 0, 20]

